# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'miniproject.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 752)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.inputtxt = QtWidgets.QLineEdit(self.frame_4)
        self.inputtxt.setMinimumSize(QtCore.QSize(750, 0))
        self.inputtxt.setMaximumSize(QtCore.QSize(2000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inputtxt.setFont(font)
        self.inputtxt.setObjectName("inputtxt")
        self.horizontalLayout.addWidget(self.inputtxt)
        self.input = QtWidgets.QPushButton(self.frame_4)
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.gridLayout_22.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tab = QtWidgets.QTabWidget(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tab.setFont(font)
        self.tab.setToolTip("")
        self.tab.setStatusTip("")
        self.tab.setObjectName("tab")
        self.synonym_tab = QtWidgets.QWidget()
        self.synonym_tab.setObjectName("synonym_tab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.synonym_tab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_18 = QtWidgets.QFrame(self.synonym_tab)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.token_lbl_2 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.token_lbl_2.setFont(font)
        self.token_lbl_2.setObjectName("token_lbl_2")
        self.gridLayout_18.addWidget(self.token_lbl_2, 0, 0, 1, 1)
        self.synonms_txt = QtWidgets.QTextEdit(self.frame_19)
        self.synonms_txt.setObjectName("synonms_txt")
        self.gridLayout_18.addWidget(self.synonms_txt, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_19, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_18, 0, 0, 1, 1)
        self.tab.addTab(self.synonym_tab, "")
        self.antynym_tab = QtWidgets.QWidget()
        self.antynym_tab.setObjectName("antynym_tab")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.antynym_tab)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_22 = QtWidgets.QFrame(self.antynym_tab)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_22)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.stop_lbl_2 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stop_lbl_2.setFont(font)
        self.stop_lbl_2.setObjectName("stop_lbl_2")
        self.gridLayout_21.addWidget(self.stop_lbl_2, 0, 0, 1, 1)
        self.antynyms_txt = QtWidgets.QTextEdit(self.frame_23)
        self.antynyms_txt.setObjectName("antynyms_txt")
        self.gridLayout_21.addWidget(self.antynyms_txt, 1, 0, 1, 1)
        self.gridLayout_20.addWidget(self.frame_23, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_22, 0, 0, 1, 1)
        self.tab.addTab(self.antynym_tab, "")
        self.gridLayout_11.addWidget(self.tab, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_3, 1, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.frame)
        self.save_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_24.addWidget(self.save_btn, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.hed_txt = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.hed_txt.setFont(font)
        self.hed_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.hed_txt.setObjectName("hed_txt")
        self.gridLayout.addWidget(self.hed_txt, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_2, 0, 0, 1, 1)
        self.exit_btn = QtWidgets.QPushButton(self.frame)
        self.exit_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit_btn.setFont(font)
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout_24.addWidget(self.exit_btn, 3, 0, 1, 1)
        self.gridLayout_25.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Enter Text"))
        self.input.setText(_translate("MainWindow", "Start"))
        self.token_lbl_2.setText(_translate("MainWindow", "Synonyms"))
        self.tab.setTabText(self.tab.indexOf(self.synonym_tab), _translate("MainWindow", "Synonyms"))
        self.stop_lbl_2.setText(_translate("MainWindow", "Antynoms"))
        self.tab.setTabText(self.tab.indexOf(self.antynym_tab), _translate("MainWindow", "Antynoms"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.hed_txt.setText(_translate("MainWindow", "Synonyms and Antynoms by NLP"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))

