# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_mini2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 623)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.txt_rd_btn = QtWidgets.QRadioButton(self.splitter)
        self.txt_rd_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_rd_btn.setFont(font)
        self.txt_rd_btn.setObjectName("txt_rd_btn")
        self.file_rd_btn = QtWidgets.QRadioButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_rd_btn.setFont(font)
        self.file_rd_btn.setObjectName("file_rd_btn")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 85, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_edit = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.input_edit.setFont(font)
        self.input_edit.setObjectName("input_edit")
        self.horizontalLayout.addWidget(self.input_edit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.browse_btn = QtWidgets.QPushButton(self.frame_2)
        self.browse_btn.setObjectName("browse_btn")
        self.gridLayout.addWidget(self.browse_btn, 1, 1, 1, 1)
        self.start_btn = QtWidgets.QPushButton(self.frame_2)
        self.start_btn.setObjectName("start_btn")
        self.gridLayout.addWidget(self.start_btn, 1, 2, 1, 1)
        self.gridLayout_11.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setStatusTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.token_tab = QtWidgets.QWidget()
        self.token_tab.setObjectName("token_tab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.token_tab)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_16 = QtWidgets.QFrame(self.token_tab)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.token_lbl = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.token_lbl.setFont(font)
        self.token_lbl.setObjectName("token_lbl")
        self.gridLayout_2.addWidget(self.token_lbl, 0, 0, 1, 1)
        self.tokn_txt = QtWidgets.QTextEdit(self.frame_17)
        self.tokn_txt.setObjectName("tokn_txt")
        self.gridLayout_2.addWidget(self.tokn_txt, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_17, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.token_tab, "")
        self.stop_tab = QtWidgets.QWidget()
        self.stop_tab.setObjectName("stop_tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.stop_tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_14 = QtWidgets.QFrame(self.stop_tab)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stop_lbl = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stop_lbl.setFont(font)
        self.stop_lbl.setObjectName("stop_lbl")
        self.gridLayout_4.addWidget(self.stop_lbl, 0, 0, 1, 1)
        self.stop_txt = QtWidgets.QTextEdit(self.frame_15)
        self.stop_txt.setObjectName("stop_txt")
        self.gridLayout_4.addWidget(self.stop_txt, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_15, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.stop_tab, "")
        self.stemming_tab = QtWidgets.QWidget()
        self.stemming_tab.setObjectName("stemming_tab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.stemming_tab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_20 = QtWidgets.QFrame(self.stemming_tab)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_21)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stem_lbl = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stem_lbl.setFont(font)
        self.stem_lbl.setObjectName("stem_lbl")
        self.gridLayout_7.addWidget(self.stem_lbl, 0, 0, 1, 1)
        self.stem_txt = QtWidgets.QTextEdit(self.frame_21)
        self.stem_txt.setObjectName("stem_txt")
        self.gridLayout_7.addWidget(self.stem_txt, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_21, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_20, 0, 0, 1, 1)
        self.tabWidget.addTab(self.stemming_tab, "")
        self.chunking_tab = QtWidgets.QWidget()
        self.chunking_tab.setObjectName("chunking_tab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.chunking_tab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_10 = QtWidgets.QFrame(self.chunking_tab)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.chunk_lbl = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.chunk_lbl.setFont(font)
        self.chunk_lbl.setObjectName("chunk_lbl")
        self.gridLayout_8.addWidget(self.chunk_lbl, 0, 0, 1, 1)
        self.lematize_txt = QtWidgets.QTextEdit(self.frame_11)
        self.lematize_txt.setObjectName("lematize_txt")
        self.gridLayout_8.addWidget(self.lematize_txt, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_11, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.chunking_tab, "")
        self.gridLayout_10.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_3, 1, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.frame)
        self.save_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_11.addWidget(self.save_btn, 2, 0, 1, 1)
        self.syn_btn = QtWidgets.QPushButton(self.frame)
        self.syn_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.syn_btn.setFont(font)
        self.syn_btn.setObjectName("syn_btn")
        self.gridLayout_11.addWidget(self.syn_btn, 3, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_12.addWidget(self.frame_4, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_rd_btn.setText(_translate("MainWindow", "By Text"))
        self.file_rd_btn.setText(_translate("MainWindow", "By File"))
        self.label.setText(_translate("MainWindow", "Enter Text"))
        self.browse_btn.setText(_translate("MainWindow", "..."))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.token_lbl.setText(_translate("MainWindow", "Tokenization Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.token_tab), _translate("MainWindow", "Tokenization"))
        self.stop_lbl.setText(_translate("MainWindow", "Stop Words Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stop_tab), _translate("MainWindow", "Stop Words"))
        self.stem_lbl.setText(_translate("MainWindow", "Stemming Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stemming_tab), _translate("MainWindow", "Stemming"))
        self.chunk_lbl.setText(_translate("MainWindow", "Lemmatization Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chunking_tab), _translate("MainWindow", "Lemmatization"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.syn_btn.setText(_translate("MainWindow", "Synynoms"))

